# target: src/main.py

puzzle:
  size: 4  # 4x4 grid for 15-puzzle

heuristics:
  manhattan_distance: true
  linear_conflict: true
  misplaced_tiles: true

solver:
  max_iterations: 1000000  # prevent infinite loops
  timeout_seconds: 30  # maximum solving time
