# target: src/main.py

puzzle:
  size: 4  # 4x4 grid for 15-puzzle

heuristics:
  default: "manhattan"  # default heuristic to use
  available:
    - "manhattan"    # sum of horizontal/vertical distances
    - "hamming"      # number of tiles out of place
    - "linear_conflict"  # manhattan + linear conflicts

solver:
  max_iterations: 1000000  # prevent infinite loops
  timeout_seconds: 30  # maximum solving time
