defaults:
  - model: googlenet # so far we have only lenet and googlenet
  - trainer: default
  - logger: null
  - optimizer: default # Add optimizer to defaults
  - paths: default # Add paths to defaults
