# Hydra configuration
defaults:
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}_${now:%H-%M}
  job:
    name: sigmoid_l2_run  # Job name  
    chdir: false        # Do not change working directory

data:
  n_samples: 1000
  normalization_method: "l2"  # "l1", "l2", or None

training:
  epochs: 500
  learning_rate: 0.1
  use_relu: false  # true for ReLU, false for sigmoid
  use_gpu: true   # true for GPU acceleration, false for CPU
