# Hydra configuration
defaults:
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}_${hydra.data.normalization_method}_${training.use_relu}           # example: outputs/training_run_l2_true
  job:
    name: training_run  # Job name  
    chdir: false        # Do not change working directory

data:
  n_samples: 1000
  normalization_method: "l2"  # "l1", "l2", or None

training:
  epochs: 500
  learning_rate: 0.1
  use_relu: true  # true for ReLU, false for sigmoid
  use_gpu: true   # true for GPU acceleration, false for CPU
