# Hydra configuration
defaults:
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}_${now:%H-%M}
  job:
    name: ReLU_l1_run  # Job name  
    chdir: false        # Do not change working directory

data:
  n_samples: 1000
  normalization_method: "l1"  # "l1", "l2", or None

training:
  epochs: 2000
  learning_rate: 0.15
  use_relu: true  # true for ReLU, false for sigmoid
  use_gpu: false   # true for GPU acceleration, false for CPU
