name: mnist-kmeans
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # Machine learning
  - scikit-learn>=1.0.0
  
  # Data visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Progress bars
  - tqdm>=4.62.0
  
  # Jupyter notebook support
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  
  # Additional utilities
  - pandas>=1.3.0
  
  # Development tools (optional)
  - pip>=21.0.0
  
  # Pip dependencies (if needed)
  - pip:
    - # Add any pip-only packages here if needed
